---
title: "rice_oxi"
author: "Chosen_Obih"
date: "2023-12-19"
output: html_document
---
load required libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.show = 'asis')
library(tidyverse)
library(ggplot2)
```

set working dir and read-in data
```{r}
setwd("/home/chosen/Desktop/Rice_GWAS_project/data/")
data <- read.csv("oxi_data.csv", header = TRUE)
```


```{r}
data_long <- data %>%
  pivot_longer("Protein":"ProtOx", names_to = "Oxidative_stress", values_to = "Value")
```

```{r echo=FALSE, fig.height=12, fig.show='asis', fig.width=15}
ggplot(data_long, aes(x = Value, fill = Treatment)) +
  geom_density(alpha = 0.5) +  # Add density plots for each treatment group
  scale_fill_manual(values = c("#00AFBB", "#FC4E07")) +
  facet_wrap(~ Oxidative_stress, scales = "free") +  # Create a separate plot for each variable
  labs(title = "Density Plot of Treatment Groups",
       x = "Value",
       y = "Density") +
  theme_minimal()
```

Create a separate plot for each oxidative stress parameter. There must be a more convenient way to make this separate plots. I will check.
```{r plot1, echo=FALSE, fig.cap="Ascorbate Oxidase"}
ggplot(data_long, aes(x = Value, fill = Treatment)) +
  geom_density(alpha = 0.5) +
  scale_fill_manual(values = c("#00AFBB", "#FC4E07")) +
  labs(title = "Density Plot for Ascorbate Oxidase",
      x = "Value",
       y = "Density")
```

